// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Query struct {
}

type UploadVideoInput struct {
	Title        string `json:"title"`
	Description  string `json:"description"`
	Duration     int    `json:"duration"`
	ThumbnailURL string `json:"thumbnailUrl"`
	File         string `json:"file"`
}

type Video struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Duration     int       `json:"duration"`
	ThumbnailURL string    `json:"thumbnailUrl"`
	VideoURL     string    `json:"videoUrl"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}
